### ISSUE TITLE
Not available through jspm?

### ISSUE THREAD

**Issue by ctjhoa** [Vheissu/aurelia-cookie#1]
Hi,
useful plugin but I can install it. Here is what I've got:
```
ctjhoa@localhost ~/aurelia % jspm install aurelia-cookie
     Updating registry cache...

err  Repo jspm:aurelia-cookie not found. Perhaps try jspm install npm:aurelia-cookie.

warn Installation changes not saved.
```

**Comment by Vheissu** [comment]
Hi yes,

I haven't put this up on NPM or JSPM just yet. I honestly forgot I can do that though.

**Comment by emcga** [comment]
I would love to use this also, but I would like to use jspm to install it.

**Comment by ctjhoa** [comment]
@Vheissu at least instructions to install aurelia-cookie seems to be a good idea.

**Comment by emcga** [comment]
I had the same issue. I changed all of the functions in cookie.js to static. That seemed to work for me. If you notice some functions static and some are not.

**Comment by emcga** [comment]
@ctjhoa are you trying to use this with Aurelia? If so you can just import the cookie.js file in your view-model and use Cookie.get() and Cookie.set() functions to get and set cookies respectively. 

```javascript
import {Cookie} from 'some-path/cookie.js'

export class foo{

      bar(){
              Cookie.get('cookie-name');
              Cookie.set('cookie-name', 'cookie data', 'object of options');
      }
}

**Comment by emcga** [comment]
@ctjhoa if you decide to make everything static you will have to change the parse function as follows...
From:
```javascript

static parse(str) {
    var obj = {};
    var pairs = str.split(/ *; */);
    var pair;

    if ('' == pairs[0]) {
      return obj;
    }

    for (let i = 0; i < pairs.length; ++i) {
      pair = pairs[i].split('=');
      obj[decode(pair[0])] = decode(pair[1]);
    }

    return obj;
  }
```


To:

```javascript
static parse(str) {
    var obj = {};
    var pairs = str.split(/ *; */);
    var pair;

    if ('' == pairs[0]) {
      return obj;
    }

    for (let i = 0; i < pairs.length; ++i) {
      pair = pairs[i].split('=');
      obj[this.decode(pair[0])] = this.decode(pair[1]);
    }

    return obj;
  }
```

So all you are doing is adding "this" to the decode functions

**Comment by ctjhoa** [comment]
@emcga yeah thanks it's work now but it's against the rules to hacked a plugin manually :P 
Thanks any way.

**Comment by emcga** [comment]
@ctjhoa Yea, I agree. I didn't really want to modify it. Maybe the original issue was because half of the functions were static and the other half were public. Try removing the static keyword from the functions and see if it will operate normally. Just a thought.

**Comment by emcga** [comment]
I guess any way we look at it we will me modifying the original code. Glad I could help some.

**Comment by Vheissu** [comment]
Definitely available through Jspm and currently working.
