### ISSUE TITLE
d.ts file placed at the root of dist folder breaks tsc

### ISSUE THREAD

**Issue by nexbit** [Vheissu/aurelia-cookie#16]
Using `aurelia-cli` 0.20.0 and importing `aurelia-cookie` results in a compilation error due to incorrect reference to the `dist/index.d.ts` file, that contains an unresolvable reference to `./cookie` module.

The contents of the `index.d.ts` file is pretty much self-explanatory:

```
import { Cookie } from './cookie';
export declare function configure(aurelia: any): void;
export { Cookie };
```

How is the first import supposed to work, if the file is placed in the `dist` folder?

The last part of `build.sh` script must be removed:

```
## Create single .d.ts file
cp dist/amd/index.d.ts dist/
```

And the `package.json` must reference one of the `index.d.ts` files inside loaders directories, in this case `amd`:

```
"typings": "dist/amd/index.d.ts"
```

If you want I could open a PR to fix this..
Thx,
P.

**Comment by Vheissu** [comment]
This has been fixed in 1.0.10
