### ISSUE TITLE
No index.js in dist folders

### ISSUE THREAD

**Issue by Tseberechts** [Vheissu/aurelia-cookie#4]
There is no index.js in the dist folder. Because of this, the plugin won't work in webpack. will try to resolve and issue a pull request.

**Comment by Tseberechts** [comment]
I suggest replacing the build.js file with the one in the plugin skeleton. Using this, it works as intended.

**Comment by bartlenaerts** [comment]
Thanks for fixing this. Can you also publish the new version to NPM?

**Comment by Vheissu** [comment]
Can confirm the latest version has index files in the dist folders. Preparing another release with some other naming fixes and paths issues resolved as well.

**Comment by Vheissu** [comment]
Can confirm the latest version has index files in the dist folders. Preparing another release with some other naming fixes and paths issues resolved as well.
